language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without tools
script: "bundle exec rake spec"
after_success:
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.4.0
  - 2.3
  - 2.2
  - rbx-3
  - jruby-9.1.6.0
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
