language: ruby
dist: trusty
sudo: required
cache: bundler
services:
  - postgresql
  - mysql
bundler_args: --without tools benchmarks
before_script:
  - psql -c 'create database rom_factory;' -U postgres
  - mysql -u root -e 'create database rom_factory;'
  - rvm get master
script: "bundle exec rake spec"
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - rbx-3
  - jruby-9.1.8.0
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
