language: ruby
sudo: false
services:
  - postgresql
  - mysql
bundler_args: --without tools benchmarks
before_script:
  - psql -c 'create database rom_factory;' -U postgres
script: "bundle exec rake spec"
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.5.0
  - 2.4.2
  - 2.3.6
  - jruby-9.1.13.0
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
